[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 800
via_ir = true
fs_permissions = [{ access = "read-write", path = "./deployments" }]
gas_reports = ["TapRegistry", "TapExecutor", "MultiTap", "TapFactory"]

[rpc_endpoints]
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[fuzz]
runs = 512

[invariant]
runs = 256
